#ifndef VEHICULE_H
#define VEHICULE_H

class Vehicule
{
public:
    Vehicule(int,int);
    // CETTE CLASSE EST DITE CLASSE ABSTRAITE CAR ELLE CONTIENT UNE FONCTION VIRTUELLE PURE
    // ON PEUT JUSTE UTILISER DES POINTEUR QUI CONTIENNENT DES ADRESSE DES OBJETS DES CLASSE FILLES
    virtual void afficherInfo() const = 0;
    virtual ~Vehicule();
protected:
    int m_annee;
    int m_prix;
};

// NOTE IMPORTANTE:
// LES METHODES STATIQUE OBEISSENT AUX REGLES DE L'HERITAGE
// DONC UNE METHODES STATIQUE DANS privat: NE PEUT PAS ETRE UTILISER DEHORS DE LA CLASSE MERE.
// C'EST LE MEME PRINCIPE LES ATTRIBUTS private: NE SERONT PAS HERITIE DANS LES CLASSE FILLES.

#endif // VEHICULE_H
